# Generated by Django 5.0.7 on 2025-03-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Anulado'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
    ]
